### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sealwestrow** [WebPolyglot/SystemaPlus-test#1]

**Comment by AleksandrTabanakov** [comment]
Отправку на почту на данном этапе я отключил, дабы избежать лишнего спама. Остальное в целом должно все работать. Написал об этом в редми

**Comment by AleksandrTabanakov** [comment]
Отправку на почту на данном этапе я отключил, дабы избежать лишнего спама. Остальное в целом должно все работать. Написано об этом в редми
